
# Site Settings
locale                   : "en"
title                    : "pdfcpu"
title_separator          : "-"
name                     : "Horst Rutter"
description              : "A PDF Processor in Golang"
url                      : "localhost"
baseurl                  : ""
repository               : "gernotstarke/pdfunit"
teaser                   : ""
words_per_minute         : 

twitter:
  username               : 


# Site Author
author:
  name             : "Horst Rutter"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : ""
  location         : "Vienna"
  email            : ""
  github           : "pdfcpu"
  twitter          : "@horst_vie"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 0 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
github: [metadata]

  
# Reading Files
include:
  - .htaccess
  - _pages
  - _posts

exclude:
  - config
  - Gemfile
  - LICENSE
  - package.json
  - Rakefile
  - README
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
