version: "2.0"

services:
  pdfcpu-jekyll-site:
    build: .
    image: pdfcpu-site
    command: jekyll serve --trace --host 0.0.0.0 --watch --incremental --config _config.yml,_config-dev.yml
    environment:
      - JEKYLL_ENV=development
    volumes:
      - ./:/srv/jekyll
    ports:
      - 4000:4000
